# Generated by Django 2.2.1 on 2019-05-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0001_initial'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.ManyToManyField(to='company_app.Company')),
                ('product_name', models.ManyToManyField(to='product_app.Product')),
            ],
        ),
    ]
